auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Hyper Hamster
url: "http://dongliye.cn/blog"
feed: /atom.xml
author_info: <a href="http://dongliye.cn/">Mukosame</a>
